import type { Scenario } from '../types/rapid-ai'

export const scenarios: Scenario[] = [
  // ─── Scenario 1: Healthy ────────────────────────────────
  {
    id: 'healthy',
    name: 'Healthy Pump',
    description: 'Pump train running within all normal parameters. No faults detected.',
    ai_insight: `This pump train is operating in excellent condition. All vibration parameters are well within acceptable limits, with an overall RMS of 1.8 mm/s — comfortably below the 8.0 mm/s threshold. The entropy analysis confirms stable energy distribution (SI = 0.85), indicating the machine's energy is flowing freely through all system elements with no signs of restriction or degradation. No fault initiators were matched, and the trend is flat over the last 90 days. Recommended action: continue routine monitoring on the current schedule. No intervention needed for at least 6 months based on current trajectory.`,
    response: {
      schema_version: '1.0',
      trace_id: 'demo-healthy-001',
      asset_id: 'PUMP-101-DE',
      final_severity_level: 'normal',
      final_severity_score: 0.12,
      confidence: 0.88,
      health_stage: 'Healthy',
      rul_days: 487,
      risk_index: 7.2,
      recommended_action: 'Vibration re-measure (confirmation run)',
      recommended_window: 'Monitor',
      reliability_metrics: {
        beta_base: 1.5,
        beta_adj: 1.644,
        eta_base_hours: 50000,
        eta_adj_hours: 46600,
        hazard_rate: 0.00000312,
        bathtub_phase: 'useful_life',
        pf_interval_position: 0.08,
        weibull_failure_prob_30d: 0.0021,
        weibull_rul_days: 487,
        nowlan_heap_pattern: 'E',
      },
      execution_time_ms: 12.4,
      module_trace: {
        module0: {
          module: 'Module0_DataGuard',
          status: 'pass',
          block: false,
          quality_score: 0.98,
          flags: { flatline: false, nan_present: false, clipping_detected: false, dropout_detected: false, unit_mismatch: false, sampling_rate_suspect: false, short_signal: false, frequency_invalid: false, timestamp_gap: false, outlier_burst: false },
          reasons: [],
          metrics: { sample_count: 8192, nan_fraction: 0, std_dev: 0.42, rms: 1.8, peak: 3.2, crest_factor: 1.78, kurtosis: 3.1, clip_fraction: 0 },
        },
        moduleA: {
          module: 'ModuleA_TrendEngine',
          overall_rms: 1.8,
          peak: 3.2,
          kurtosis: 3.1,
          crest_factor: 1.78,
          baseline: 1.5,
          ratio_to_baseline: 1.2,
          degradation: 0.04,
          severity_score: 0.12,
          severity_level: 'normal',
          trend_classification: 'machine',
        },
        moduleB: {
          module: 'ModuleB_Initiators',
          component: 'afb',
          num_matches: 0,
          matched_rules: [],
          confidence: 0.0,
        },
        moduleBplus: {
          module: 'ModuleBPlus_SlopeIntelligence',
          slope: 0.001,
          slope_change: 0.0002,
          instability_index: 0.05,
          trend_class: 'Stable',
          severity_score: 0.003,
        },
        moduleBpp: {
          module: 'ModuleBPP_SEDL',
          SE: 0.22,
          TE: 0.18,
          DE: 0.15,
          dSE_dt: 0.001,
          SI: 0.85,
          stability_state: 'Stable',
          severity_level: 'normal',
          triggered_rules: ['SR01'],
        },
        moduleC: {
          module: 'ModuleC_Fusion',
          system_type: 'pump_train_horizontal',
          profile_id: 'PROFILE_PUMP_A',
          SSI: 0.15,
          system_state: 'stable',
          top_contributors: [],
          recommended_action: 'monitor',
        },
        moduleD: {
          module: 'ModuleD_FaultMechanism',
          degradation_stage: 'Healthy',
          rul_band: '> 6 months',
          escalation_level: 'Level_0',
          recommended_action: 'Continue monitoring',
        },
        moduleE: {
          module: 'ModuleE_MaintenancePlan',
          plan_items: [
            { rank: 1, priority_score: 18.5, window: 'Next shutdown', action_id: 'ACT001', action_title: 'Vibration re-measure (confirmation run)', justification: 'Confirm trend before committing to intervention', verification: 'Compare new RMS to previous within ±10%' },
          ],
          total_actions: 1,
        },
        moduleF: {
          module: 'ModuleF_Governance',
          RUL_days: 487,
          failure_probability_30d: 0.0021,
          confidence: 0.88,
          risk_index: 7.2,
          recommended_window: 'Monitor',
          reliability_metrics: {
            beta_base: 1.5, beta_adj: 1.644, eta_base_hours: 50000, eta_adj_hours: 46600,
            hazard_rate: 0.00000312, bathtub_phase: 'useful_life', pf_interval_position: 0.08,
            weibull_failure_prob_30d: 0.0021, weibull_rul_days: 487, nowlan_heap_pattern: 'E',
          },
        },
      },
    },
  },

  // ─── Scenario 2: Degrading (Bearing Wear) ──────────────
  {
    id: 'degrading',
    name: 'Bearing Wear',
    description: 'Early bearing degradation detected. Drift trend with rising entropy.',
    ai_insight: `This pump train shows early-stage bearing degradation on the drive-end anti-friction bearing. The overall RMS has risen to 4.2 mm/s (ratio to baseline = 1.68×), with a clear drift trend (slope = 0.032/day) in the log domain. Module B has identified BPFO (outer race) defect signatures with 72% confidence. The entropy analysis shows spectral energy beginning to spread (SE = 0.48, SI = 0.62), consistent with increased randomness from bearing surface damage. The system is in the early wear-out phase of the bathtub curve (β_adj = 1.86). Based on current trajectory, estimated remaining useful life is 92 days. Recommended: schedule bearing lubrication within 7 days, and plan bearing replacement within the next planned shutdown window (< 90 days). Delay beyond 60 days risks transition to unstable state.`,
    response: {
      schema_version: '1.0',
      trace_id: 'demo-degrading-001',
      asset_id: 'PUMP-101-DE',
      final_severity_level: 'warning',
      final_severity_score: 0.52,
      confidence: 0.74,
      health_stage: 'Degrading',
      rul_days: 92,
      risk_index: 31.2,
      recommended_action: 'Bearing lubrication / grease replenishment',
      recommended_window: 'Planned',
      reliability_metrics: {
        beta_base: 1.5,
        beta_adj: 1.924,
        eta_base_hours: 50000,
        eta_adj_hours: 36500,
        hazard_rate: 0.0000218,
        bathtub_phase: 'wear_out',
        pf_interval_position: 0.42,
        weibull_failure_prob_30d: 0.0834,
        weibull_rul_days: 92,
        nowlan_heap_pattern: 'C',
      },
      execution_time_ms: 18.7,
      module_trace: {
        module0: {
          module: 'Module0_DataGuard',
          status: 'pass',
          block: false,
          quality_score: 0.95,
          flags: { flatline: false, nan_present: false, clipping_detected: false, dropout_detected: false, unit_mismatch: false, sampling_rate_suspect: false, short_signal: false, frequency_invalid: false, timestamp_gap: false, outlier_burst: false },
          reasons: [],
          metrics: { sample_count: 8192, nan_fraction: 0, std_dev: 1.1, rms: 4.2, peak: 8.4, crest_factor: 2.0, kurtosis: 4.8, clip_fraction: 0 },
        },
        moduleA: {
          module: 'ModuleA_TrendEngine',
          overall_rms: 4.2,
          peak: 8.4,
          kurtosis: 4.8,
          crest_factor: 2.0,
          baseline: 2.5,
          ratio_to_baseline: 1.68,
          degradation: 0.27,
          severity_score: 0.55,
          severity_level: 'warning',
          trend_classification: 'machine',
        },
        moduleB: {
          module: 'ModuleB_Initiators',
          component: 'afb',
          num_matches: 2,
          matched_rules: [
            { rule_id: 'AFB03', initiator: 'Outer Race Defect (BPFO)', diagnosis: 'bearing outer race wear, early stage', score: 1.8, triggered_conditions: [{ expr: 'kurtosis', op: '>=', threshold: 4.0, value: 4.8 }] },
            { rule_id: 'AFB06', initiator: 'Shaft Imbalance', diagnosis: 'imbalance affecting bearing', score: 1.2, triggered_conditions: [{ expr: 'H/V', op: '>=', threshold: 1.2, value: 1.25 }] },
          ],
          confidence: 0.72,
        },
        moduleBplus: {
          module: 'ModuleBPlus_SlopeIntelligence',
          slope: 0.032,
          slope_change: 0.005,
          instability_index: 0.18,
          trend_class: 'Drift',
          severity_score: 0.256,
        },
        moduleBpp: {
          module: 'ModuleBPP_SEDL',
          SE: 0.48,
          TE: 0.35,
          DE: 0.28,
          dSE_dt: 0.012,
          SI: 0.62,
          stability_state: 'Drifting',
          severity_level: 'watch',
          triggered_rules: ['SR02'],
        },
        moduleC: {
          module: 'ModuleC_Fusion',
          system_type: 'pump_train_horizontal',
          profile_id: 'PROFILE_PUMP_A',
          SSI: 0.45,
          system_state: 'degrading',
          top_contributors: ['afb'],
          recommended_action: 'alert',
        },
        moduleD: {
          module: 'ModuleD_FaultMechanism',
          degradation_stage: 'Degrading',
          rul_band: '1–6 months',
          escalation_level: 'Level_1',
          recommended_action: 'Schedule inspection',
        },
        moduleE: {
          module: 'ModuleE_MaintenancePlan',
          plan_items: [
            { rank: 1, priority_score: 52.3, window: '7 days', action_id: 'ACT002', action_title: 'Bearing lubrication / grease replenishment', justification: 'High frequency or temperature rise indicates lubrication deficit', verification: 'HF amplitude and temperature return to baseline within 24h' },
            { rank: 2, priority_score: 52.3, window: '7 days', action_id: 'ACT005', action_title: 'Bearing replacement (scheduled)', justification: 'BPFO/BPFI signatures with acceleration confirms bearing defect', verification: 'Post-replacement vibration within acceptance limits' },
            { rank: 3, priority_score: 52.3, window: '7 days', action_id: 'ACT001', action_title: 'Vibration re-measure (confirmation run)', justification: 'Confirm trend before committing to intervention', verification: 'Compare new RMS to previous within ±10%' },
          ],
          total_actions: 3,
        },
        moduleF: {
          module: 'ModuleF_Governance',
          RUL_days: 92,
          failure_probability_30d: 0.0834,
          confidence: 0.74,
          risk_index: 31.2,
          recommended_window: 'Planned',
          reliability_metrics: {
            beta_base: 1.5, beta_adj: 1.924, eta_base_hours: 50000, eta_adj_hours: 36500,
            hazard_rate: 0.0000218, bathtub_phase: 'wear_out', pf_interval_position: 0.42,
            weibull_failure_prob_30d: 0.0834, weibull_rul_days: 92, nowlan_heap_pattern: 'C',
          },
        },
      },
    },
  },

  // ─── Scenario 3: Critical (Imminent Failure) ───────────
  {
    id: 'critical',
    name: 'Imminent Failure',
    description: 'Critical bearing failure imminent. Accelerating trend, entropy destabilizing.',
    ai_insight: `CRITICAL ALERT — This pump train requires immediate attention. The drive-end bearing is showing advanced degradation with imminent failure risk. Overall RMS has reached 7.6 mm/s (ratio to baseline = 3.04×), accelerating at 0.15/day with slope increasing. Kurtosis of 12.5 indicates severe impulsive impacts from surface spalling. Module B confirms advanced inner race defect (BPFI) and cage damage with 89% confidence. Entropy analysis shows critical instability (SI = 0.38, SE = 0.72) — energy flow is severely disrupted, consistent with Dibyendu De's Theory of Imperfections indicating imminent functional failure. The Weibull model estimates only 3 days of remaining useful life (β_adj = 2.71, wear-out phase). 30-day failure probability is 98.5%. RECOMMENDED: Emergency shutdown at the earliest safe opportunity. Inspect bearing, prepare replacement parts. Do not delay — operating beyond 48 hours in this condition risks catastrophic failure with secondary damage to shaft, seals, and coupling.`,
    response: {
      schema_version: '1.0',
      trace_id: 'demo-critical-001',
      asset_id: 'PUMP-101-DE',
      final_severity_level: 'alarm',
      final_severity_score: 0.87,
      confidence: 0.91,
      health_stage: 'Critical',
      rul_days: 3,
      risk_index: 87.0,
      recommended_action: 'Emergency shutdown / trip recommendation',
      recommended_window: 'Immediate',
      reliability_metrics: {
        beta_base: 1.5,
        beta_adj: 2.544,
        eta_base_hours: 50000,
        eta_adj_hours: 26600,
        hazard_rate: 0.000342,
        bathtub_phase: 'wear_out',
        pf_interval_position: 0.91,
        weibull_failure_prob_30d: 0.985,
        weibull_rul_days: 3,
        nowlan_heap_pattern: 'B',
      },
      execution_time_ms: 22.1,
      module_trace: {
        module0: {
          module: 'Module0_DataGuard',
          status: 'pass',
          block: false,
          quality_score: 0.92,
          flags: { flatline: false, nan_present: false, clipping_detected: false, dropout_detected: false, unit_mismatch: false, sampling_rate_suspect: false, short_signal: false, frequency_invalid: false, timestamp_gap: false, outlier_burst: true },
          reasons: ['Outlier burst detected (impulsive content)'],
          metrics: { sample_count: 8192, nan_fraction: 0, std_dev: 3.8, rms: 7.6, peak: 22.8, crest_factor: 3.0, kurtosis: 12.5, clip_fraction: 0 },
        },
        moduleA: {
          module: 'ModuleA_TrendEngine',
          overall_rms: 7.6,
          peak: 22.8,
          kurtosis: 12.5,
          crest_factor: 3.0,
          baseline: 2.5,
          ratio_to_baseline: 3.04,
          degradation: 0.81,
          severity_score: 0.95,
          severity_level: 'alarm',
          trend_classification: 'machine',
        },
        moduleB: {
          module: 'ModuleB_Initiators',
          component: 'afb',
          num_matches: 3,
          matched_rules: [
            { rule_id: 'AFB02', initiator: 'Inner Race Defect (BPFI)', diagnosis: 'bearing inner race advanced damage', score: 2.8, triggered_conditions: [{ expr: 'kurtosis', op: '>=', threshold: 8.0, value: 12.5 }, { expr: 'crest_factor', op: '>=', threshold: 2.5, value: 3.0 }] },
            { rule_id: 'AFB05', initiator: 'Cage Defect', diagnosis: 'bearing cage damage, advanced', score: 2.2, triggered_conditions: [{ expr: 'HF', op: '>=', threshold: 5.0, value: 8.4 }] },
            { rule_id: 'AFB06', initiator: 'Shaft Imbalance', diagnosis: 'imbalance affecting bearing', score: 1.5, triggered_conditions: [{ expr: 'H/V', op: '>=', threshold: 1.2, value: 1.35 }] },
          ],
          confidence: 0.89,
        },
        moduleBplus: {
          module: 'ModuleBPlus_SlopeIntelligence',
          slope: 0.15,
          slope_change: 0.08,
          instability_index: 0.72,
          trend_class: 'Accelerating',
          severity_score: 0.90,
        },
        moduleBpp: {
          module: 'ModuleBPP_SEDL',
          SE: 0.72,
          TE: 0.65,
          DE: 0.55,
          dSE_dt: 0.045,
          SI: 0.38,
          stability_state: 'Critical_Instability',
          severity_level: 'alarm',
          triggered_rules: ['SR05'],
        },
        moduleC: {
          module: 'ModuleC_Fusion',
          system_type: 'pump_train_horizontal',
          profile_id: 'PROFILE_PUMP_A',
          SSI: 0.82,
          system_state: 'critical',
          top_contributors: ['afb', 'coupling'],
          recommended_action: 'shutdown_or_trip',
        },
        moduleD: {
          module: 'ModuleD_FaultMechanism',
          degradation_stage: 'Critical',
          rul_band: '< 7 days',
          escalation_level: 'Level_3',
          recommended_action: 'Immediate intervention required',
        },
        moduleE: {
          module: 'ModuleE_MaintenancePlan',
          plan_items: [
            { rank: 1, priority_score: 96.8, window: 'Immediate', action_id: 'ACT008', action_title: 'Emergency shutdown / trip recommendation', justification: 'Critical SSI with accelerating trend, imminent failure risk', verification: 'Machine isolated, inspection completed before restart' },
            { rank: 2, priority_score: 96.8, window: 'Immediate', action_id: 'ACT005', action_title: 'Bearing replacement (scheduled)', justification: 'BPFO/BPFI signatures with acceleration confirms bearing defect', verification: 'Post-replacement vibration within acceptance limits' },
            { rank: 3, priority_score: 96.8, window: 'Immediate', action_id: 'ACT004', action_title: 'Balance correction (single / dual plane)', justification: '1× dominance with horizontal preference indicates imbalance', verification: '1× amplitude reduced by ≥50% post-correction' },
          ],
          total_actions: 3,
        },
        moduleF: {
          module: 'ModuleF_Governance',
          RUL_days: 3,
          failure_probability_30d: 0.985,
          confidence: 0.91,
          risk_index: 87.0,
          recommended_window: 'Immediate',
          reliability_metrics: {
            beta_base: 1.5, beta_adj: 2.544, eta_base_hours: 50000, eta_adj_hours: 26600,
            hazard_rate: 0.000342, bathtub_phase: 'wear_out', pf_interval_position: 0.91,
            weibull_failure_prob_30d: 0.985, weibull_rul_days: 3, nowlan_heap_pattern: 'B',
          },
        },
      },
    },
  },
]
